"use client";

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {Download,LogOut,PackagePlus,Pencil,Search,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import type {Category,Product} from '@/lib/catalog';
import ProductImage from '@/app/product-image';
import {getCatalog,isAdmin,supabase,uploadProductImage} from '@/lib/supabase';
import {downloadBlob,downloadFullBackup,downloadSource,exportData} from '@/lib/backup';

const emptyProduct:Product={id:'',title:'',category:'nubes',description:'',price:80,compareAtPrice:0,sizes:[],tags:'',audience:'',themeGroup:'',estimatedDays:'3 a 5 días hábiles',featured:false,imageUrl:'',galleryUrls:[]};
const statuses:Record<string,string>={nuevo:'Nuevo',confirmado:'Confirmado',en_preparacion:'En preparación',enviado:'Enviado',completado:'Completado',cancelado:'Cancelado'};
type Order={id:string;customer_name:string;customer_phone:string;total:number;status:string;created_at:string;payload:{customerCity?:string;shipping?:string;checkoutNotes?:string;items?:{product:{title:string};quantity:number;sizeLabel:string;personalization:string;notes:string;unitPrice:number}[]}};

export default function AdminClient(){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[authorized,setAuthorized]=useState(false),[checking,setChecking]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [products,setProducts]=useState<Product[]>([]),[categories,setCategories]=useState<Category[]>([]),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[editing,setEditing]=useState<Product|null>(null),[saving,setSaving]=useState(false);
 const [tab,setTab]=useState('productos'),[orders,setOrders]=useState<Order[]>([]),[editingCategory,setEditingCategory]=useState<Category|null>(null),[busy,setBusy]=useState(false),[backupProgress,setBackupProgress]=useState('');
 const load=async()=>{const data=await getCatalog();setProducts(data.products);setCategories(data.categories);};
 useEffect(()=>{
  let active=true;
  const check=async()=>{try{const admin=await isAdmin();if(active){setAuthorized(admin);if(admin)await load();}}catch{if(active)setError('No se pudo comprobar la sesión.');}finally{if(active)setChecking(false);}};
  void check();
  const {data:{subscription}}=supabase.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'){setAuthorized(false);setProducts([]);setOrders([]);}});
  return()=>{active=false;subscription.unsubscribe();};
 },[]);
 useEffect(()=>{if(authorized&&tab==='pedidos'){supabase.from('segeda_orders').select('*').order('created_at',{ascending:false}).limit(500).then(({data,error})=>{if(error)setError('No se pudieron cargar los pedidos.');else setOrders(data as Order[]);});}},[tab,authorized]);
 const filtered=useMemo(()=>products.filter(p=>(category==='all'||p.category===category)&&p.title.toLowerCase().includes(query.toLowerCase())),[products,query,category]);
 const verify=async(event:FormEvent)=>{event.preventDefault();setSaving(true);setError('');try{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw new Error('Revisa tu correo y contraseña.');if(!await isAdmin()){await supabase.auth.signOut();throw new Error('Esta cuenta no tiene acceso al panel.');}setAuthorized(true);setPassword('');await load();}catch(e){setError(e instanceof Error?e.message:'No se pudo iniciar sesión.');}finally{setSaving(false);}};
 const signOut=async()=>{await supabase.auth.signOut();setAuthorized(false);setPassword('');setError('');};
 const save=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!editing)return;setSaving(true);setError('');try{const form=new FormData(event.currentTarget);let imageUrl=String(form.get('imageUrl')||'').trim();const file=form.get('imageFile');if(file instanceof File&&file.size)imageUrl=await uploadProductImage(file);if(imageUrl&&!/^https:\/\//.test(imageUrl)&&!imageUrl.startsWith('/'))throw new Error('La imagen debe usar una dirección HTTPS.');const replaced=imageUrl!==editing.imageUrl;const galleryUrls=replaced?[imageUrl,...(editing.galleryUrls||[]).slice(1)].filter(Boolean):editing.galleryUrls||[imageUrl];const product:Product={...editing,id:editing.id||crypto.randomUUID(),title:String(form.get('title')||'').trim(),category:String(form.get('category')),description:String(form.get('description')||''),price:Number(form.get('price')),compareAtPrice:Number(form.get('compareAtPrice')||0),audience:String(form.get('audience')||''),themeGroup:String(form.get('themeGroup')||''),estimatedDays:String(form.get('estimatedDays')||''),featured:form.get('featured')==='on',imageUrl,galleryUrls};if(product.sizes?.some(s=>!s.label.trim()||!Number.isFinite(s.price)||s.price<0))throw new Error('Revisa las medidas y sus precios.');const {error}=await supabase.from('segeda_products').upsert({id:String(product.id),category:product.category,data:product,updated_at:new Date().toISOString()});if(error)throw new Error('No se pudo guardar el producto.');setEditing(null);await load();setNotice('Producto guardado.');}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setSaving(false);}};
 const remove=async(product:Product)=>{if(!confirm(`¿Eliminar ${product.title}?`))return;const {error}=await supabase.from('segeda_products').delete().eq('id',String(product.id));if(error)setError('No se pudo eliminar el producto.');else await load();};
 const saveCategory=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!editingCategory)return;setSaving(true);setError('');try{const form=new FormData(event.currentTarget);let image=String(form.get('image')||'');const file=form.get('imageFile');if(file instanceof File&&file.size)image=await uploadProductImage(file);const item={...editingCategory,name:String(form.get('name')),short:String(form.get('short')),description:String(form.get('description')||''),image,featured:form.get('featured')==='on'};const {error}=await supabase.from('segeda_categories').upsert({id:item.id,data:item,updated_at:new Date().toISOString()});if(error)throw new Error('No se pudo guardar la categoría.');setEditingCategory(null);await load();setNotice('Categoría guardada.');}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setSaving(false);}};
 const runBackup=async(kind:'full'|'data'|'source')=>{setBusy(true);setError('');setBackupProgress('Preparando la descarga…');try{if(kind==='full')await downloadFullBackup(setBackupProgress);else if(kind==='source')await downloadSource();else downloadBlob(new Blob([JSON.stringify(await exportData(),null,2)],{type:'application/json'}),'Segeda-datos.json');setBackupProgress('Descarga preparada. Guarda el archivo en un lugar tuyo.');}catch(e){setError(e instanceof Error?e.message:'No se pudo preparar la descarga.');setBackupProgress('');}finally{setBusy(false);}};
 const changePassword=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const element=event.currentTarget,form=new FormData(element),next=String(form.get('newPassword'));if(next!==form.get('repeatPassword')){setError('Las contraseñas no coinciden.');return;}setSaving(true);const {error}=await supabase.auth.updateUser({password:next});setSaving(false);if(error)setError('No se pudo cambiar la contraseña. Vuelve a iniciar sesión e inténtalo nuevamente.');else{element.reset();setNotice('Contraseña actualizada.');setError('');}};

 if(checking)return <main className="admin-login"><div className="admin-loading" role="status">Comprobando tu acceso…</div></main>;
 if(!authorized)return <main className="admin-login"><form onSubmit={verify}><div className="admin-mark">SH</div><p className="eyebrow">Tu espacio de trabajo</p><h1>Segeda Home</h1><p>Ingresa para cuidar tu catálogo y atender tus pedidos.</p><Label htmlFor="admin-email">Correo electrónico</Label><Input id="admin-email" type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="username" required/><Label htmlFor="admin-password">Contraseña</Label><Input id="admin-password" type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password" required/><Button disabled={saving} type="submit">{saving?'Ingresando…':'Ingresar al panel'}</Button>{error&&<p className="admin-error" role="alert">{error}</p>}<a href="/catalogo">Volver a la tienda</a></form></main>;

 return <main className="admin-shell"><aside className="admin-sidebar"><div><span className="admin-mark">SH</span><strong>Segeda Home</strong></div><nav>{[['productos','Productos'],['categorias','Categorías'],['pedidos','Pedidos'],['respaldo','Respaldo y acceso']].map(([id,title])=><button key={id} className={tab===id?'active':''} onClick={()=>{setTab(id);setError('');setNotice('');}}>{title}</button>)}<a href="/catalogo">Ver tienda</a></nav><button onClick={signOut}><LogOut size={16}/>Cerrar sesión</button></aside><section className="admin-content">{error&&<p className="admin-error" role="alert">{error}</p>}{notice&&<p className="admin-success" role="status">{notice}</p>}
 {tab==='productos'&&<><header><div><p className="eyebrow">Cada detalle cuenta</p><h1>Productos</h1><p>{products.length} diseños disponibles</p></div><Button onClick={()=>{setError('');setEditing({...emptyProduct,id:crypto.randomUUID()});}}><PackagePlus/>Nuevo producto</Button></header><div className="admin-filters"><div><Search/><Input placeholder="Buscar por nombre" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="Filtrar categoría" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Todas las categorías</option>{categories.map(c=><option key={c.id} value={c.id}>{c.short}</option>)}</select></div><div className="admin-table"><Table><TableHeader><TableRow><TableHead>Producto</TableHead><TableHead>Categoría</TableHead><TableHead>Precio</TableHead><TableHead>Entrega</TableHead><TableHead>Acciones</TableHead></TableRow></TableHeader><TableBody>{filtered.map(p=><TableRow key={p.id}><TableCell><div className="product-cell"><ProductImage src={p.imageUrl} alt={p.title}/><strong>{p.title}</strong></div></TableCell><TableCell>{categories.find(c=>c.id===p.category)?.short||p.category}</TableCell><TableCell>S/{p.price}</TableCell><TableCell>{p.estimatedDays||'—'}</TableCell><TableCell><div className="row-actions"><Button size="icon" variant="ghost" aria-label={`Editar ${p.title}`} onClick={()=>{setError('');setEditing({...p});}}><Pencil/></Button><Button size="icon" variant="ghost" aria-label={`Eliminar ${p.title}`} onClick={()=>void remove(p)}><Trash2/></Button></div></TableCell></TableRow>)}</TableBody></Table></div></>}
 {tab==='categorias'&&<><header><div><p className="eyebrow">El mundo Segeda</p><h1>Categorías</h1><p>{categories.length} colecciones</p></div></header><div className="admin-category-grid">{categories.map(c=><article key={c.id}><ProductImage src={c.image} alt={c.name}/><h2>{c.short}</h2><p>{products.filter(p=>p.category===c.id).length} productos</p><Button variant="outline" onClick={()=>{setError('');setEditingCategory({...c});}}><Pencil/>Editar categoría</Button></article>)}</div></>}
 {tab==='pedidos'&&<><header><div><p className="eyebrow">Acompaña cada compra</p><h1>Pedidos</h1><p>Los pedidos enviados desde el carrito aparecen aquí.</p></div></header>{!orders.length?<div className="admin-empty">Aún no hay pedidos registrados.</div>:<div className="admin-orders">{orders.map(order=><article key={order.id}><div><h2>{order.customer_name}</h2><time>{new Date(order.created_at).toLocaleString('es-PE',{timeZone:'America/Lima'})}</time><p>{order.customer_phone} · {order.payload.customerCity}</p><strong>S/{Number(order.total).toFixed(2)}</strong><select aria-label="Estado del pedido" value={order.status} onChange={async e=>{const status=e.target.value;const {error}=await supabase.from('segeda_orders').update({status}).eq('id',order.id);if(error)setError('No se pudo actualizar el pedido.');else setOrders(list=>list.map(item=>item.id===order.id?{...item,status}:item));}}>{Object.entries(statuses).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div><ul>{order.payload.items?.map((item,i)=><li key={i}>{item.quantity} × {item.product.title} · {item.sizeLabel}{item.personalization&&` · ${item.personalization}`}{item.notes&&` · ${item.notes}`}</li>)}</ul><p>Envío: {order.payload.shipping}</p>{order.payload.checkoutNotes&&<p>{order.payload.checkoutNotes}</p>}<small>Referencia: {order.id}</small></article>)}</div>}</>}
 {tab==='respaldo'&&<><header><div><p className="eyebrow">Tu tienda, contigo</p><h1>Respaldo y acceso</h1><p>Guarda una copia de tu trabajo y cuida tu acceso.</p></div></header><div className="admin-backup-grid"><article><h2>Código de la web</h2><p>El proyecto y las instrucciones para publicarlo en otro alojamiento. Descarga también los datos actuales.</p><Button disabled={busy} onClick={()=>void runBackup('source')}><Download/>Descargar proyecto</Button></article><article><h2>Datos e imágenes actuales</h2><p>Catálogo, categorías, pedidos y todas las imágenes. La descarga puede tardar unos minutos.</p><Button disabled={busy} onClick={()=>void runBackup('full')}><Download/>Descargar respaldo completo</Button><button className="admin-text-button" disabled={busy} onClick={()=>void runBackup('data')}>Solo datos</button></article></div>{backupProgress&&<p role="status">{backupProgress}</p>}<form className="admin-password-form" onSubmit={changePassword}><h2>Cambiar contraseña</h2><Label htmlFor="new-password">Nueva contraseña</Label><Input id="new-password" name="newPassword" type="password" minLength={12} autoComplete="new-password" required/><Label htmlFor="repeat-password">Repetir contraseña</Label><Input id="repeat-password" name="repeatPassword" type="password" minLength={12} autoComplete="new-password" required/><Button disabled={saving} type="submit">Actualizar contraseña</Button></form></>}
 </section>
 <Dialog open={Boolean(editing)} onOpenChange={open=>!open&&setEditing(null)}><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>{editing?.title?'Editar producto':'Nuevo producto'}</DialogTitle></DialogHeader>{editing&&<form onSubmit={save}><Label>Nombre<Input name="title" defaultValue={editing.title} required/></Label><div className="form-row"><Label>Categoría<select name="category" defaultValue={editing.category}>{categories.map(c=><option key={c.id} value={c.id}>{c.short}</option>)}</select></Label><Label>Precio<Input name="price" type="number" min="0" step="0.01" defaultValue={editing.price} required/></Label><Label>Precio anterior<Input name="compareAtPrice" type="number" min="0" step="0.01" defaultValue={editing.compareAtPrice||0}/></Label></div><Label>Descripción<Textarea name="description" defaultValue={editing.description}/></Label><fieldset className="admin-sizes"><legend>Medidas o presentaciones</legend>{editing.sizes?.map((size,index)=><div key={index}><Input aria-label="Medida" value={size.label} onChange={e=>setEditing({...editing,sizes:editing.sizes?.map((s,i)=>i===index?{...s,label:e.target.value}:s)})}/><Input aria-label="Precio de la medida" type="number" min="0" step="0.01" value={size.price} onChange={e=>setEditing({...editing,sizes:editing.sizes?.map((s,i)=>i===index?{...s,price:Number(e.target.value)}:s)})}/><button type="button" aria-label="Quitar medida" onClick={()=>setEditing({...editing,sizes:editing.sizes?.filter((_,i)=>i!==index)})}>×</button></div>)}<button type="button" onClick={()=>setEditing({...editing,sizes:[...(editing.sizes||[]),{label:'',price:editing.price}]})}>+ Agregar medida</button></fieldset><div className="form-row"><Label>Público<Input name="audience" defaultValue={editing.audience}/></Label><Label>Tema<Input name="themeGroup" defaultValue={editing.themeGroup}/></Label><Label>Tiempo de entrega<Input name="estimatedDays" defaultValue={editing.estimatedDays}/></Label></div><Label>Dirección de la imagen<Input name="imageUrl" defaultValue={editing.imageUrl}/></Label><Label>Subir una imagen<Input name="imageFile" type="file" accept="image/jpeg,image/png,image/webp,image/avif"/></Label><Label><input name="featured" type="checkbox" defaultChecked={editing.featured}/> Destacar producto</Label>{error&&<p className="admin-error" role="alert">{error}</p>}<Button type="submit" disabled={saving}>{saving?'Guardando…':'Guardar producto'}</Button></form>}</DialogContent></Dialog>
 <Dialog open={Boolean(editingCategory)} onOpenChange={open=>!open&&setEditingCategory(null)}><DialogContent className="admin-dialog"><DialogHeader><DialogTitle>Editar categoría</DialogTitle></DialogHeader>{editingCategory&&<form onSubmit={saveCategory}><Label>Nombre completo<Input name="name" defaultValue={editingCategory.name} required/></Label><Label>Nombre breve<Input name="short" defaultValue={editingCategory.short} required/></Label><Label>Descripción<Textarea name="description" defaultValue={editingCategory.description}/></Label><Label>Dirección de la imagen<Input name="image" defaultValue={editingCategory.image}/></Label><Label>Subir una imagen<Input name="imageFile" type="file" accept="image/jpeg,image/png,image/webp,image/avif"/></Label><Label><input name="featured" type="checkbox" defaultChecked={editingCategory.featured}/> Destacar colección</Label>{error&&<p className="admin-error">{error}</p>}<Button disabled={saving} type="submit">Guardar categoría</Button></form>}</DialogContent></Dialog>
 </main>;
}
