import {useState,type FormEvent,type ReactNode} from 'react';
import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {supabase} from '@/lib/supabase';
import {financeRpc,recordFinance,voidFinance,type FinanceData} from '@/lib/finance-api';
import {GENERAL,billPaid,costMetrics,expenseTypes,kindLabels,methods,money,orderPaid,orderStatuses,parseAmount,peruToday,toCents,type FinanceBill,type FinanceTransaction,type MovementKind,type StoreOrder} from '@/lib/finance';
export type FinanceDialog=
 |{type:'movement';id:string;kind:MovementKind;order?:StoreOrder;bill?:FinanceBill}
 |{type:'bill';id:string}|{type:'budget';section:string}|{type:'cost';section:string}
 |{type:'order';order:StoreOrder}|{type:'void';transaction:FinanceTransaction}|{type:'cancel-bill';bill:FinanceBill};
export const Field=({label,children,hint}:{label:string;children:ReactNode;hint?:string})=><label className="fin-field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>;
const amount=(form:FormData,key:string,zero=false)=>parseAmount(String(form.get(key)||''),zero)/100;
const text=(form:FormData,key:string)=>String(form.get(key)||'').trim();
const MoneyInput=({name,value,required=true}:{name:string;value?:string|number;required?:boolean})=><input name={name} inputMode="decimal" placeholder="0.00" defaultValue={value} required={required} autoComplete="off"/>;
function SelectOptions({values}:{values:Record<string,string>}){return Object.entries(values).map(([v,label])=><option key={v} value={v}>{label}</option>);}
function CostPreview({formValues}:{formValues:Record<string,string>}){
 const n=(key:string)=>Number((formValues[key]||'').replace(',','.'));
 if(['unit_price','unit_cost','fixed_cost','expected_units'].some(k=>formValues[k]===''||formValues[k]===undefined)||Object.values(formValues).some(v=>!Number.isFinite(Number(v.replace(',','.')))||Number(v.replace(',','.'))<0))return <p className="fin-note">Completa tus costos para ver la estimación. No se guardará ningún cobro ni gasto.</p>;
 const result=costMetrics({unit_price:n('unit_price'),unit_cost:n('unit_cost'),fixed_cost:n('fixed_cost'),expected_units:n('expected_units'),fee_percent:n('fee_percent')});
 return <div className="fin-preview"><p>Aporte de cada unidad: <strong>{money(result.contribution)}</strong></p><p>Punto de equilibrio: <strong>{result.breakEven===null?'El precio no cubre el costo variable':`${result.breakEven} unidades`}</strong></p><p>Utilidad prevista: <strong>{money(result.forecast)}</strong></p><small>Precio − costo variable − comisión; luego se descuentan los costos fijos.</small></div>;
}
export default function FinanceDialogs({dialog,data,month,defaultSection,onClose,onSaved}:{dialog:FinanceDialog;data:FinanceData;month:string;defaultSection:string;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [busy,setBusy]=useState(false),[error,setError]=useState('');
 const plan=dialog.type==='cost'?data.plans.find(p=>p.section_id===dialog.section&&p.month.startsWith(month)):undefined;
 const [costValues,setCostValues]=useState<Record<string,string>>(()=>Object.fromEntries(['unit_price','unit_cost','fixed_cost','expected_units','fee_percent'].map(k=>[k,String(plan?.[k as keyof typeof plan]??(k==='fee_percent'||(dialog.type==='cost'&&dialog.section===GENERAL&&k!=='fixed_cost')?0:''))])));
 const [status,setStatus]=useState(dialog.type==='order'?dialog.order.status:'');
 const titles={movement:dialog.type==='movement'?`Registrar ${kindLabels[dialog.kind].toLowerCase()}`:'',bill:'Nueva cuenta por pagar',budget:'Presupuesto mensual',cost:'Costos y precios',order:'Estado y fechas del pedido',void:'Anular movimiento', 'cancel-bill':'Anular cuenta por pagar'};
 const sections=(name:string,value=defaultSection,disabled=false)=><select name={name} defaultValue={value==='all'?GENERAL:value} disabled={disabled}><SelectOptions values={Object.fromEntries(data.sections.map(s=>[s.id,s.name]))}/></select>;
 const submit=async(e:FormEvent<HTMLFormElement>)=>{
  e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);
  try{
   if(dialog.type==='movement'){
    const section=dialog.bill?.section_id||(['contribution','withdrawal'].includes(dialog.kind)?GENERAL:text(f,'section'));
    await recordFinance({p_id:dialog.id,p_kind:dialog.kind,p_amount:amount(f,'amount'),p_date:text(f,'date'),p_description:text(f,'description'),p_section:section||GENERAL,p_method:text(f,'method'),p_expense_type:dialog.kind==='expense'?(dialog.bill?.expense_type||text(f,'expense_type')):'',p_order:dialog.order?.id||null,p_reference:text(f,'reference'),p_bill:dialog.bill?.id||null,p_behavior:dialog.kind==='expense'?(dialog.bill?.expense_behavior||text(f,'expense_behavior')):''});
   }else if(dialog.type==='bill'){
    const values={id:dialog.id,vendor:text(f,'vendor'),description:text(f,'description'),section_id:text(f,'section'),amount:amount(f,'amount'),due_on:text(f,'due'),expense_type:text(f,'expense_type'),expense_behavior:text(f,'expense_behavior')};
    const {error:err}=await supabase.from('segeda_finance_bills').insert(values);
    if(err){if(err.code!=='23505')throw new Error('No se pudo guardar la cuenta por pagar.');const {data:existing,error:readError}=await supabase.from('segeda_finance_bills').select('*').eq('id',dialog.id).single();if(readError||!existing||Object.entries(values).some(([k,v])=>String(existing[k])!==String(v)))throw new Error('Este formulario ya fue guardado con otros datos. Ciérralo y actualiza la lista.');}
   }else if(dialog.type==='budget'){
    const {error:err}=await supabase.from('segeda_finance_budgets').upsert({month:`${month}-01`,section_id:text(f,'section'),income_target:amount(f,'income',true),expense_limit:amount(f,'expense',true),notes:text(f,'notes'),updated_at:new Date().toISOString()},{onConflict:'month,section_id'});if(err)throw new Error('No se pudo guardar el presupuesto.');
   }else if(dialog.type==='cost'){
    const units=Number(text(f,'expected_units')),fee=Number(text(f,'fee_percent').replace(',','.'));
    if(!Number.isInteger(units)||units<0||units>1000000||!Number.isFinite(fee)||fee<0||fee>=100||Math.abs(fee*100-Math.round(fee*100))>0.00001)throw new Error('Revisa las unidades y la comisión (de 0 a 99.99%).');
    const {error:err}=await supabase.from('segeda_finance_cost_plans').upsert({month:`${month}-01`,section_id:dialog.section,unit_price:amount(f,'unit_price',true),unit_cost:amount(f,'unit_cost',true),fixed_cost:amount(f,'fixed_cost',true),expected_units:units,fee_percent:fee,notes:text(f,'notes'),updated_at:new Date().toISOString()},{onConflict:'month,section_id'});if(err)throw new Error('No se pudo guardar el plan de costos.');
   }else if(dialog.type==='order'){
    await financeRpc('segeda_finance_order_update',{p_id:dialog.order.id,p_status:status,p_due:text(f,'due')||null,p_completed:text(f,'completed')||null});
   }else if(dialog.type==='void')await voidFinance(dialog.transaction.id,text(f,'reason'));
   else await financeRpc('segeda_finance_cancel_bill',{p_id:dialog.bill.id,p_reason:text(f,'reason')});
   onClose();await onSaved();
  }catch(err){setError(err instanceof Error?err.message:'No se pudo guardar.');}finally{setBusy(false);}
 };
 const budget=dialog.type==='budget'?data.budgets.find(b=>b.month.startsWith(month)&&b.section_id===dialog.section):undefined;
 const terms=dialog.type==='order'?data.terms.find(t=>t.order_id===dialog.order.id):undefined;
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="fin-dialog" onInteractOutside={e=>{if(busy)e.preventDefault();}}><DialogHeader><DialogTitle>{titles[dialog.type]}</DialogTitle><DialogDescription>{dialog.type==='cost'||dialog.type==='budget'?`Plan de ${month}. Los objetivos no crean movimientos de dinero.`:'Registra los datos con los que llevarás el control de tu negocio.'}</DialogDescription></DialogHeader><form onSubmit={submit} className="fin-form">
 {dialog.type==='movement'&&<>
 {(dialog.order||dialog.bill)&&<p className="fin-note">{dialog.order?`${dialog.order.customer_name||'Cliente por confirmar'} · ${dialog.kind==='refund'?'Disponible para devolver':'Saldo pendiente'}: ${money(dialog.kind==='refund'?orderPaid(dialog.order.id,data.transactions):toCents(dialog.order.total)-orderPaid(dialog.order.id,data.transactions))}`:`${dialog.bill!.vendor} · Pendiente: ${money(toCents(dialog.bill!.amount)-billPaid(dialog.bill!.id,data.transactions))}`}</p>}
 <div className="fin-form-grid"><Field label="Importe (S/)"><MoneyInput name="amount"/></Field><Field label="Fecha del movimiento"><input name="date" type="date" defaultValue={peruToday()} min="1900-01-01" max={peruToday()} required/></Field></div>
 <Field label="Concepto"><input name="description" maxLength={250} defaultValue={dialog.order?`${dialog.kind==='refund'?'Devolución':'Cobro'} · ${dialog.order.customer_name||'Cliente por confirmar'}`:dialog.bill?.description||''} placeholder="Ej.: compra de MDF para cuadros" required/></Field>
 {dialog.order?<p className="fin-note">El importe se reparte entre las secciones del pedido según sus productos, conservando cada céntimo.</p>:['contribution','withdrawal'].includes(dialog.kind)?<p className="fin-note">Se registra en General y modifica la caja, sin aumentar ni reducir las ventas. Los intereses de préstamos se registran como gasto.</p>:<Field label="Sección">{sections('section',dialog.bill?.section_id||defaultSection,!!dialog.bill)}</Field>}
 {dialog.kind==='expense'&&<div className="fin-form-grid"><Field label="Tipo de gasto"><select name="expense_type" defaultValue={dialog.bill?.expense_type||'materiales'} disabled={!!dialog.bill}><SelectOptions values={expenseTypes}/></select></Field><Field label="Comportamiento" hint="Fijo: existe aunque no vendas. Variable: crece con los pedidos."><select name="expense_behavior" defaultValue={dialog.bill?.expense_behavior||'variable'} disabled={!!dialog.bill}><option value="variable">Variable</option><option value="fixed">Fijo</option></select></Field></div>}
 <div className="fin-form-grid"><Field label="Medio de pago"><select name="method"><SelectOptions values={methods}/></select></Field><Field label="Referencia (opcional)"><input name="reference" maxLength={150} placeholder="N.º de operación o comprobante"/></Field></div>
 </>}
 {dialog.type==='bill'&&<><Field label="Proveedor / a quién pagar"><input name="vendor" maxLength={150} required/></Field><Field label="Concepto"><input name="description" maxLength={250} required/></Field><div className="fin-form-grid"><Field label="Importe total (S/)"><MoneyInput name="amount"/></Field><Field label="Vencimiento"><input name="due" type="date" min="1900-01-01" required defaultValue={peruToday()}/></Field></div><Field label="Sección">{sections('section')}</Field><div className="fin-form-grid"><Field label="Tipo de gasto"><select name="expense_type"><SelectOptions values={expenseTypes}/></select></Field><Field label="Comportamiento"><select name="expense_behavior"><option value="variable">Variable</option><option value="fixed">Fijo</option></select></Field></div><p className="fin-note">Esta cuenta queda pendiente. El gasto se registra cuando agregas su pago, incluido un pago parcial.</p></>}
 {dialog.type==='budget'&&<><Field label="Sección">{sections('section',dialog.section,true)}<input type="hidden" name="section" value={dialog.section}/></Field><div className="fin-form-grid"><Field label="Meta de cobros (S/)"><MoneyInput name="income" value={budget?.income_target}/></Field><Field label="Límite de gastos pagados (S/)"><MoneyInput name="expense" value={budget?.expense_limit}/></Field></div><Field label="Notas"><textarea name="notes" maxLength={500} defaultValue={budget?.notes} placeholder="Qué quieres conseguir este mes"/></Field><p className="fin-note">Puedes ingresar cero. El avance compara cobros netos de devoluciones y gastos realmente pagados.</p></>}
 {dialog.type==='cost'&&<><p className="fin-note">{data.sections.find(s=>s.id===dialog.section)?.name}. Estima un costo promedio por unidad de esta sección. Incluye material, mano de obra, empaque y merma en el costo variable.</p><div className="fin-form-grid">{[['unit_price','Precio promedio por unidad (S/)'],['unit_cost','Costo variable por unidad (S/)'],['fixed_cost','Costos fijos mensuales (S/)'],['fee_percent','Comisión sobre ventas (%)'],['expected_units','Unidades que esperas vender']].filter(([k])=>dialog.section!==GENERAL||k==='fixed_cost').map(([k,label])=><Field key={k} label={label}><input name={k} inputMode={k==='expected_units'?'numeric':'decimal'} value={costValues[k]} onChange={e=>setCostValues({...costValues,[k]:e.target.value})} required placeholder="0"/></Field>)}</div>{dialog.section===GENERAL&&['unit_price','unit_cost','expected_units','fee_percent'].map(k=><input key={k} type="hidden" name={k} value="0"/>)}<Field label="Supuestos / notas"><textarea name="notes" maxLength={500} defaultValue={plan?.notes} placeholder="Ej.: costo promedio del set de 3, incluido empaque"/></Field>{dialog.section===GENERAL?<p className="fin-note">Este costo se descuenta una sola vez de la utilidad total. No se necesitan unidades ni precios para los gastos compartidos.</p>:<CostPreview formValues={costValues}/>}<p className="fin-note">Registra alquiler u otros costos compartidos una sola vez en General. Las comisiones se estiman sobre ventas antes de devoluciones. No incluye impuestos, depreciación ni ajustes de inventario.</p></>}
 {dialog.type==='order'&&<><p>{dialog.order.customer_name||'Cliente por confirmar'} · {money(toCents(dialog.order.total))}</p><Field label="Estado"><select value={status} onChange={e=>setStatus(e.target.value)}><SelectOptions values={orderStatuses}/></select></Field><Field label="Fecha límite para cobrar (opcional)"><input name="due" type="date" min="1900-01-01" defaultValue={terms?.due_on||''}/></Field><Field label="Fecha de finalización" hint="Se usa para reconocer la venta y estimar su utilidad. Los adelantos siguen siendo cobros."><input name="completed" type="date" min="1900-01-01" max={peruToday()} key={status==='completado'?'complete':'other'} defaultValue={terms?.completed_on||(status==='completado'?peruToday():'')} required={status==='completado'||!!terms?.completed_on}/></Field><p className="fin-note">Cambiar el estado no registra dinero. Si cancelas un pedido cobrado, registra su devolución por separado. La fecha de finalización conserva el historial de ventas.</p></>}
 {(dialog.type==='void'||dialog.type==='cancel-bill')&&<><p className="fin-note">{dialog.type==='void'?`${dialog.transaction.description} · ${money(toCents(dialog.transaction.amount))}`:dialog.bill.description}. El registro se conserva en el historial con su motivo.</p><Field label="Motivo de anulación"><textarea name="reason" minLength={5} maxLength={500} required placeholder="Explica la corrección"/></Field></>}
 {error&&<p className="admin-error" role="alert">{error}</p>}<div className="fin-dialog-actions"><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Volver</Button><Button type="submit" disabled={busy}>{busy?'Guardando…':dialog.type==='void'||dialog.type==='cancel-bill'?'Confirmar anulación':'Guardar'}</Button></div>
 </form></DialogContent></Dialog>;
}
