"use client";
import {useEffect,useMemo,useState,type ReactNode} from 'react';
import {ArrowDownLeft,ArrowUpRight,BarChart3,CalendarDays,ChevronLeft,ChevronRight,Download,Info,Plus,RefreshCw,Search,Wallet} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,Legend,Line,LineChart,ReferenceLine,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {Button} from '@/components/ui/button';
import {downloadBlob} from '@/lib/backup';
import {loadFinance,type FinanceData} from '@/lib/finance-api';
import {GENERAL,billPaid,costMetrics,dayLabel,expenseTypes,financeCsv,kindLabels,methods,money,monthLabel,orderComposition,orderPaid,orderStatuses,peruToday,profitBySection,sectionAmount,stepMonth,summarize,toCents,type MovementKind,type StoreOrder} from '@/lib/finance';
import FinanceDialogs,{type FinanceDialog} from './finance-dialogs';
import './finance.css';
const tabs=[['summary','Resumen'],['orders','Pedidos y cobros'],['income','Ingresos'],['expenses','Gastos'],['bills','Por pagar'],['budgets','Presupuestos'],['profit','Utilidad por sección'],['costs','Costos y precios']] as const;
type Tab=typeof tabs[number][0];
function Empty({children}:{children:ReactNode}){return <div className="fin-empty"><Wallet size={28}/><p>{children}</p></div>;}
function Stat({title,value,detail,tone='neutral'}:{title:string;value:string;detail:string;tone?:string}){return <article className={`fin-stat ${tone}`}><span>{title}</span><strong>{value}</strong><small>{detail}</small></article>;}
function SectionHeading({title,description,children}:{title:string;description:string;children?:ReactNode}){return <div className="fin-section-heading"><div><h2>{title}</h2><p>{description}</p></div>{children}</div>;}
const chartMoney=(value:unknown)=>money(Number(value));
const shortMoney=(value:number)=>`S/${new Intl.NumberFormat('es-PE',{notation:'compact',maximumFractionDigits:1}).format(value/100)}`;
export default function OrdersFinance(){
 const [data,setData]=useState<FinanceData|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [tab,setTab]=useState<Tab>('summary'),[month,setMonth]=useState(peruToday().slice(0,7)),[section,setSection]=useState('all'),[dialog,setDialog]=useState<FinanceDialog|null>(null);
 const [search,setSearch]=useState(''),[orderFilter,setOrderFilter]=useState('pending'),[showVoided,setShowVoided]=useState(false),[limit,setLimit]=useState(30);
 const refresh=async()=>{setLoading(true);setError('');try{setData(await loadFinance());}catch(e){setError(e instanceof Error?e.message:'No se pudo actualizar el panel.');}finally{setLoading(false);}};
 useEffect(()=>{let active=true;loadFinance().then(value=>{if(active)setData(value);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
 const summary=useMemo(()=>data?summarize(data.transactions,data.sections,month,section):null,[data,month,section]);
 const profit=useMemo(()=>data?profitBySection(data.orders,data.terms,data.transactions,data.sections,data.plans,month):[],[data,month]);
 const go=(next:Tab)=>{setTab(next);setSearch('');setLimit(30);};
 const movement=(kind:MovementKind,order?:StoreOrder)=>setDialog({type:'movement',id:crypto.randomUUID(),kind,order});
 if(!data)return <section className="finance"><h1>Pedidos y finanzas</h1>{loading?<p role="status">Preparando tu espacio de control…</p>:<><p className="admin-error" role="alert">{error}</p><Button onClick={()=>void refresh()}>Volver a cargar</Button></>}</section>;
 const {transactions,sections,orders,bills,budgets,plans,terms}=data;
 const today=peruToday(),names=Object.fromEntries(sections.map(s=>[s.id,s.name]));
 const matches=(id:string)=>section==='all'||id===section;
 const orderInSection=(o:StoreOrder)=>section==='all'||Object.hasOwn(orderComposition(o,sections).revenue,section);
 const unpaidOrders=orders.filter(o=>o.status!=='cancelado'&&toCents(o.total)>orderPaid(o.id,transactions)&&orderInSection(o));
 const pendingBills=bills.filter(b=>!b.cancelled_at&&toCents(b.amount)>billPaid(b.id,transactions)&&matches(b.section_id));
 const termsMap=new Map(terms.map(t=>[t.order_id,t]));
 const dueOrders=unpaidOrders.filter(o=>{const due=termsMap.get(o.id)?.due_on;return due&&due<today;});
 const dueBills=pendingBills.filter(b=>b.due_on<today);
 const receivable=unpaidOrders.reduce((s,o)=>s+toCents(o.total)-orderPaid(o.id,transactions),0),payable=pendingBills.reduce((s,b)=>s+toCents(b.amount)-billPaid(b.id,transactions),0);
 const totals=summary!.totals,monthlyRows=summary!.rows;
 const filteredProfit=profit.filter(p=>matches(p.id));
 const incomplete=filteredProfit.filter(p=>!p.plan&&(p.revenue!==0||p.refunds!==0||p.units>0));
 const missingGeneral=(section==='all'||section===GENERAL)&&!profit.find(p=>p.id===GENERAL)?.plan;
 const profitReady=!incomplete.length&&!missingGeneral&&filteredProfit.some(p=>p.plan);
 const totalProfit=filteredProfit.reduce((sum,p)=>sum+(p.profit||0),0);
 const ledger=transactions.filter(t=>t.occurred_on.startsWith(month)&&(showVoided||!t.voided_at)&&sectionAmount(t,section)>0&&(tab==='expenses'?t.kind==='expense':t.kind!=='expense')&&`${t.description} ${t.reference} ${t.order_id||''} ${kindLabels[t.kind]}`.toLocaleLowerCase('es').includes(search.toLocaleLowerCase('es'))).sort((a,b)=>b.occurred_on.localeCompare(a.occurred_on)||b.created_at.localeCompare(a.created_at));
 const orderList=orders.filter(orderInSection).filter(o=>{const paid=orderPaid(o.id,transactions);return orderFilter==='all'||(orderFilter==='pending'?o.status!=='cancelado'&&paid<toCents(o.total):orderFilter==='refund'?o.status==='cancelado'&&paid>0:o.status===orderFilter);}).filter(o=>`${o.customer_name||'Cliente por confirmar'} ${o.customer_phone||'WhatsApp por confirmar'} ${o.id}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>b.created_at.localeCompare(a.created_at));
 const selectedBills=bills.filter(b=>matches(b.section_id)&&(showVoided||!b.cancelled_at)&&`${b.vendor} ${b.description}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>a.due_on.localeCompare(b.due_on));
 const scopeHint=tab==='orders'||tab==='bills'?'Saldos actuales de todas las fechas':`Movimientos de ${monthLabel(month)}`;
 const exportCsv=()=>downloadBlob(new Blob([financeCsv(transactions,sections,month,section)],{type:'text/csv;charset=utf-8'}),`Segeda-movimientos-${month}-${section}.csv`);
 const table=(headings:string[],body:ReactNode)=><div className="fin-table-wrap"><table className="fin-table"><thead><tr>{headings.map(h=><th key={h} scope="col">{h}</th>)}</tr></thead><tbody>{body}</tbody></table></div>;
 const more=(length:number)=>length>limit&&<Button variant="outline" className="fin-more" onClick={()=>setLimit(limit+30)}>Ver más ({length-limit} restantes)</Button>;
 return <section className="finance" aria-busy={loading}>
 <header className="fin-header"><div><p className="eyebrow">Claridad para crecer</p><h1>Pedidos y finanzas</h1><p>Cada venta, cada costo, una decisión más clara.</p></div><div className="fin-actions"><Button variant="outline" disabled={loading} onClick={()=>void refresh()}><RefreshCw size={16} className={loading?'fin-spin':''}/>Actualizar</Button><Button onClick={()=>movement('expense')} disabled={loading}><Plus size={16}/>Registrar gasto</Button></div></header>
 {error&&<p className="admin-error" role="alert">{error} {data&&'Se mantienen los últimos datos cargados.'}</p>}{notice&&<p className="admin-success" role="status">{notice}</p>}
 <nav className="fin-tabs" aria-label="Secciones de finanzas">{tabs.map(([id,label])=><button key={id} type="button" aria-current={tab===id?'page':undefined} className={tab===id?'active':''} onClick={()=>go(id)}>{label}</button>)}</nav>
 <div className="fin-toolbar"><div className="fin-month"><button aria-label="Mes anterior" disabled={tab==='orders'||tab==='bills'} onClick={()=>setMonth(stepMonth(month,-1))}><ChevronLeft size={18}/></button><label><span className="sr-only">Mes del informe</span><input type="month" value={month} min="1900-01" max="9998-12" disabled={tab==='orders'||tab==='bills'} onChange={e=>{if(/^\d{4}-\d{2}$/.test(e.target.value)){setMonth(e.target.value);setLimit(30);}}}/></label><button aria-label="Mes siguiente" disabled={tab==='orders'||tab==='bills'} onClick={()=>setMonth(stepMonth(month,1))}><ChevronRight size={18}/></button></div><label className="fin-section-select"><span className="sr-only">Filtrar sección</span><select value={section} onChange={e=>{setSection(e.target.value);setLimit(30);}}><option value="all">Todas las secciones</option>{sections.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><small>{scopeHint}</small>{tab!=='orders'&&tab!=='bills'&&<button className="fin-text-button" onClick={exportCsv}><Download size={16}/>Exportar movimientos</button>}</div>
 <div className="fin-page" key={tab}>
 {tab==='summary'&&<>
 <div className="fin-stats"><Stat title="Cobros netos" value={money(totals.net)} detail={`${money(totals.income)} cobrado − ${money(totals.refund)} devuelto`} tone="sage"/><Stat title="Gastos pagados" value={money(totals.expense)} detail="Dinero que ya salió para operar" tone="rose"/><Stat title="Flujo operativo" value={money(totals.operating)} detail="Cobros netos menos gastos pagados"/><Stat title="Utilidad estimada" value={profitReady?money(totalProfit):'Faltan costos'} detail="Pedidos finalizados, con tus costos estimados" tone="gold"/></div>
 <div className="fin-two-col"><article className="fin-card"><SectionHeading title="El ritmo del mes" description="Cobros y gastos por día. Los aportes de capital se muestran aparte."/>{summary!.active.some(t=>sectionAmount(t,section)>0)?<div className="fin-chart" role="img" aria-label={`Cobros ${money(totals.income)}, gastos ${money(totals.expense)} durante ${monthLabel(month)}`}><ResponsiveContainer width="100%" height="100%"><LineChart data={summary!.days} margin={{top:10,right:12,bottom:0,left:0}}><CartesianGrid vertical={false} stroke="#eadfd8"/><XAxis dataKey="day" tickLine={false} axisLine={false}/><YAxis width={78} tickFormatter={shortMoney} tickLine={false} axisLine={false}/><Tooltip formatter={chartMoney}/><Legend/><Line name="Cobros" dataKey="income" stroke="#648771" strokeWidth={2.5} dot={false} isAnimationActive={false}/><Line name="Gastos" dataKey="expense" stroke="#c87671" strokeWidth={2.5} dot={false} isAnimationActive={false}/><Line name="Devoluciones" dataKey="refund" stroke="#af894d" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>:<Empty>El gráfico aparecerá cuando registres tu primer movimiento de este mes.</Empty>}</article>
 <article className="fin-card"><SectionHeading title="Lo que viene" description="Pendientes actuales, aunque se hayan creado en otro mes."/><button className="fin-pending" onClick={()=>go('orders')}><span><ArrowDownLeft/>Por cobrar <small>{unpaidOrders.length} pedidos · {dueOrders.length} vencidos</small></span><strong>{money(receivable)}</strong></button><button className="fin-pending" onClick={()=>go('bills')}><span><ArrowUpRight/>Por pagar <small>{pendingBills.length} cuentas · {dueBills.length} vencidas</small></span><strong>{money(payable)}</strong></button>{section!=='all'&&<p className="fin-note">Por cobrar muestra el saldo completo de los pedidos que incluyen esta sección.</p>}<div className="fin-guide"><Info size={18}/><p>Primero registra el cobro o pago. Después revisa sus resultados. Crear un pedido o un presupuesto no mueve dinero.</p></div></article></div>
 <div className="fin-two-col"><article className="fin-card"><SectionHeading title="Caja y capital" description="Los aportes y retiros no se mezclan con el resultado operativo."/><dl className="fin-totals"><div><dt>Aportes / financiamiento</dt><dd>{money(totals.contribution)}</dd></div><div><dt>Retiros / devolución de capital</dt><dd>{money(totals.withdrawal)}</dd></div><div><dt>Variación neta de caja del mes</dt><dd>{money(totals.cash)}</dd></div></dl><p className="fin-note">Es la variación registrada, no el saldo bancario. Para empezar, registra tu saldo inicial como aporte e indica «Saldo inicial» en el concepto.</p><div className="fin-actions"><Button variant="outline" onClick={()=>movement('contribution')}>Registrar aporte</Button><Button variant="outline" onClick={()=>movement('withdrawal')}>Registrar retiro</Button></div></article>
 <article className="fin-card"><SectionHeading title="Tres conceptos, sin confusiones" description="Una guía para leer tus resultados."/><ol className="fin-explainer"><li><strong>Caja:</strong> dinero que efectivamente entra o sale, incluidos adelantos.</li><li><strong>Utilidad estimada:</strong> ventas finalizadas menos devoluciones y costos estimados. Requiere completar tus costos.</li><li><strong>Presupuesto:</strong> tu meta de cobros y límite de pagos, para comparar con la realidad.</li></ol><button className="fin-text-button" onClick={()=>go('costs')}>Completar mis costos <ArrowUpRight size={15}/></button></article></div>
 </>}
 {tab==='orders'&&<>
 <SectionHeading title="Tus pedidos, con cada cobro al día" description="Registra adelantos, saldos y devoluciones. Finalizar un pedido permite estimar su utilidad."/>
 <div className="fin-stats compact"><Stat title="Pendiente por cobrar" value={money(receivable)} detail={`${unpaidOrders.length} pedidos activos`}/><Stat title="Con vencimiento pasado" value={String(dueOrders.length)} detail="Revisa la fecha límite acordada" tone="rose"/><Stat title="Cancelados con dinero por devolver" value={String(orders.filter(o=>orderInSection(o)&&o.status==='cancelado'&&orderPaid(o.id,transactions)>0).length)} detail="La cancelación no crea una devolución automática"/></div>
 <div className="fin-filters"><label className="fin-search"><Search size={17}/><input placeholder="Buscar cliente, teléfono o referencia" aria-label="Buscar pedido" value={search} onChange={e=>{setSearch(e.target.value);setLimit(30);}}/></label><select aria-label="Estado o saldo de los pedidos" value={orderFilter} onChange={e=>{setOrderFilter(e.target.value);setLimit(30);}}><option value="pending">Con saldo pendiente</option><option value="all">Todos los pedidos</option><option value="refund">Cancelados por devolver</option>{Object.entries(orderStatuses).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></div>
 {orderList.length?<div className="fin-order-list">{orderList.slice(0,limit).map(o=>{const paid=orderPaid(o.id,transactions),left=toCents(o.total)-paid,term=termsMap.get(o.id);return <article className="fin-card fin-order" key={o.id}><div className="fin-order-heading"><div><small>{dayLabel(peruToday(new Date(o.created_at)))}</small><h3>{o.customer_name||'Cliente por confirmar'}</h3><p>{o.customer_phone||'WhatsApp por confirmar'} {o.payload.customerCity&&`· ${o.payload.customerCity}`}</p></div><span className="fin-badge">{orderStatuses[o.status]||o.status}</span></div><div className="fin-order-money"><span>Total<strong>{money(toCents(o.total))}</strong></span><span>Cobrado neto<strong>{money(paid)}</strong></span><span>{o.status==='cancelado'?'Por devolver':'Pendiente'}<strong>{money(o.status==='cancelado'?paid:left)}</strong></span></div>{term?.due_on&&<p className={term.due_on<today&&left>0&&o.status!=='cancelado'?'fin-warning':'fin-note'}><CalendarDays size={15}/>Vence {dayLabel(term.due_on)}</p>}<details><summary>Ver productos y detalles</summary><ul>{o.payload.items?.map((item,i)=><li key={i}>{item.quantity} × {item.product.title} · {item.sizeLabel}{item.personalization&&` · ${item.personalization}`}{item.notes&&` · ${item.notes}`}<small>{names[item.product.category||'']||'General'} · {money(toCents(item.unitPrice)*item.quantity)}</small></li>)}</ul><p>Envío: {o.payload.shipping||'Sin indicaciones'}</p>{o.payload.checkoutNotes&&<p>{o.payload.checkoutNotes}</p>}<small>Referencia: {o.id}</small>{term?.completed_on&&<p>Finalizado: {dayLabel(term.completed_on)}</p>}</details><div className="fin-actions"><Button disabled={loading||left<=0||o.status==='cancelado'} onClick={()=>movement('income',o)}>Registrar cobro</Button><Button variant="outline" disabled={loading||paid<=0} onClick={()=>movement('refund',o)}>Devolver</Button><button className="fin-text-button" onClick={()=>setDialog({type:'order',order:o})}>Estado y fechas</button></div></article>;})}</div>:<Empty>No hay pedidos que coincidan con este filtro. Los pedidos de tu tienda aparecerán aquí.</Empty>}{more(orderList.length)}
 </>}
 {(tab==='income'||tab==='expenses')&&<>
 <SectionHeading title={tab==='income'?'Ingresos, devoluciones y capital':'Gastos del negocio'} description={tab==='income'?'Cada cobro se registra cuando recibes el dinero. Los aportes aparecen separados de las ventas.':'Asigna cada gasto a su sección. Usa General para los costos compartidos.'}><Button onClick={()=>movement(tab==='income'?'income':'expense')} disabled={loading}><Plus size={16}/>{tab==='income'?'Cobro sin pedido':'Nuevo gasto'}</Button></SectionHeading>
 {tab==='income'&&<div className="fin-inline-actions"><button onClick={()=>go('orders')}>Cobrar un pedido</button><button onClick={()=>movement('contribution')}>Registrar aporte</button><button onClick={()=>movement('withdrawal')}>Registrar retiro</button></div>}
 <div className="fin-filters"><label className="fin-search"><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);setLimit(30);}} placeholder="Buscar concepto o referencia" aria-label="Buscar movimiento"/></label><label className="fin-check"><input type="checkbox" checked={showVoided} onChange={e=>setShowVoided(e.target.checked)}/>Incluir anulados</label></div>
 {ledger.length?table(['Fecha / tipo','Concepto y sección','Importe','Medio / referencia','Acción'],ledger.slice(0,limit).map(t=><tr key={t.id} className={t.voided_at?'fin-voided':''}><td>{dayLabel(t.occurred_on)}<small>{kindLabels[t.kind]}{t.voided_at?' · Anulado':''}</small></td><td><strong>{t.description}</strong><small>{t.allocations.filter(a=>matches(a.section_id)).map(a=>`${names[a.section_id]} (${money(toCents(a.amount))})`).join(' · ')}</small>{t.expense_type&&<small>{expenseTypes[t.expense_type]} · {t.expense_behavior==='fixed'?'Fijo':'Variable'}</small>}{t.order_id&&<small>Pedido {t.order_id.slice(0,8)}</small>}{t.bill_id&&<small>Pago de cuenta a proveedor</small>}{t.void_reason&&<small>Motivo: {t.void_reason}</small>}</td><td className={['expense','refund','withdrawal'].includes(t.kind)?'fin-negative':'fin-positive'}>{['expense','refund','withdrawal'].includes(t.kind)?'−':'+'}{money(sectionAmount(t,section))}</td><td>{methods[t.method]}<small>{t.reference||'Sin referencia'}</small></td><td>{!t.voided_at&&<button className="fin-text-button" disabled={loading} onClick={()=>setDialog({type:'void',transaction:t})}>Anular</button>}</td></tr>)):<Empty>Aún no hay movimientos para este mes y sección.</Empty>}{more(ledger.length)}
 <p className="fin-note">Para corregir un movimiento, anúlalo con un motivo y registra el correcto. El historial se conserva. La exportación incluye solo los movimientos vigentes del mes y sección elegidos.</p>
 </>}
 {tab==='bills'&&<>
 <SectionHeading title="Cuentas por pagar" description="Anticipa tus compromisos y registra cada pago sin duplicar el gasto." ><Button disabled={loading} onClick={()=>setDialog({type:'bill',id:crypto.randomUUID()})}><Plus size={16}/>Nueva cuenta</Button></SectionHeading>
 <div className="fin-stats compact"><Stat title="Saldo por pagar" value={money(payable)} detail={`${pendingBills.length} compromisos abiertos`} tone="rose"/><Stat title="Vencidos" value={money(dueBills.reduce((s,b)=>s+toCents(b.amount)-billPaid(b.id,transactions),0))} detail={`${dueBills.length} cuentas con fecha pasada`}/><Stat title="Vencen hoy" value={String(pendingBills.filter(b=>b.due_on===today).length)} detail="Organiza los pagos del día"/></div>
 <div className="fin-filters"><label className="fin-search"><Search size={17}/><input value={search} onChange={e=>{setSearch(e.target.value);setLimit(30);}} placeholder="Buscar proveedor o concepto" aria-label="Buscar cuenta por pagar"/></label><label className="fin-check"><input type="checkbox" checked={showVoided} onChange={e=>setShowVoided(e.target.checked)}/>Incluir anuladas</label></div>
 {selectedBills.length?table(['Proveedor / concepto','Vencimiento','Total','Pagado','Pendiente','Acciones'],selectedBills.slice(0,limit).map(b=>{const paid=billPaid(b.id,transactions),left=toCents(b.amount)-paid;return <tr key={b.id} className={b.cancelled_at?'fin-voided':''}><td><strong>{b.vendor}</strong><small>{b.description}</small><small>{names[b.section_id]}</small>{b.cancelled_at&&<small>Anulada: {b.cancel_reason}</small>}</td><td>{dayLabel(b.due_on)}<small className={!b.cancelled_at&&left>0&&b.due_on<today?'fin-negative':''}>{b.cancelled_at?'Anulada':left<=0?'Pagada':b.due_on<today?'Vencida':b.due_on===today?'Vence hoy':'Pendiente'}</small></td><td>{money(toCents(b.amount))}</td><td>{money(paid)}</td><td>{b.cancelled_at?'—':money(left)}</td><td><div className="fin-actions">{!b.cancelled_at&&left>0&&<Button variant="outline" disabled={loading} onClick={()=>setDialog({type:'movement',id:crypto.randomUUID(),kind:'expense',bill:b})}>Pagar</Button>}{!b.cancelled_at&&paid===0&&<button className="fin-text-button" onClick={()=>setDialog({type:'cancel-bill',bill:b})}>Anular</button>}</div></td></tr>;})):<Empty>Aún no tienes cuentas por pagar en esta sección.</Empty>}{more(selectedBills.length)}
 </>}
 {tab==='budgets'&&<>
 <SectionHeading title="Un plan para tu mes" description="Define cuánto quieres cobrar y cuánto puedes pagar en cada sección. Cero es una meta válida; sin configurar significa que aún no hay un plan."/>
 <div className="fin-budget-grid">{monthlyRows.map(row=>{const b=budgets.find(b=>b.month.startsWith(month)&&b.section_id===row.id),target=b?toCents(b.income_target):0,cap=b?toCents(b.expense_limit):0;const ratio=(actual:number,goal:number)=>goal>0?Math.min(100,Math.max(0,actual/goal*100)):actual>0?100:0;return <article key={row.id} className="fin-card"><h3>{row.name}</h3>{b?<><div className="fin-budget-line"><span>Cobros netos / meta</span><strong>{money(row.net)} / {money(target)}</strong></div><progress aria-label={`Avance de cobros de ${row.name}`} value={ratio(row.net,target)} max={100}/><small>{target===0?'Meta de cobros: cero':row.net>=target?'Meta alcanzada':`Faltan ${money(target-row.net)} para tu meta`}</small><div className="fin-budget-line"><span>Gastos / límite</span><strong>{money(row.expense)} / {money(cap)}</strong></div><progress className={row.expense>cap?'over':'expense'} aria-label={`Uso del presupuesto de ${row.name}`} value={ratio(row.expense,cap)} max={100}/><small className={row.expense>cap?'fin-negative':''}>{row.expense>cap?`Excedido en ${money(row.expense-cap)}`:`Disponible: ${money(cap-row.expense)}`}</small>{b.notes&&<p className="fin-note">{b.notes}</p>}</>:<p className="fin-note">Aún no has definido tu presupuesto para {monthLabel(month)}.</p>}<button className="fin-text-button" onClick={()=>setDialog({type:'budget',section:row.id})}>{b?'Editar presupuesto':'Crear presupuesto'}</button></article>;})}</div>
 </>}
 {tab==='profit'&&<>
 <SectionHeading title="¿Qué sección aporta más?" description="Compara ventas de pedidos finalizados y costos estimados del mes. Los adelantos y aportes de capital no son utilidad."/>
 <div className="fin-stats compact"><Stat title="Ventas netas finalizadas" value={money(filteredProfit.reduce((s,p)=>s+p.netRevenue,0))} detail="Incluye devoluciones de pedidos finalizados" tone="sage"/><Stat title="Utilidad operativa estimada" value={profitReady?money(totalProfit):'Por completar'} detail={profitReady?'Antes de impuestos y ajustes de inventario':'Completa costos de secciones con ventas y General'} tone="gold"/><Stat title="Flujo operativo real" value={money(totals.operating)} detail="Cobros netos menos pagos: puede diferir de la utilidad"/></div>
 {(incomplete.length>0||missingGeneral)&&<p className="fin-warning"><Info size={18}/>Faltan costos en {[...incomplete.map(r=>r.name),...(missingGeneral?['General (costos compartidos)']:[])].join(', ')}. No asumimos que sean cero.</p>}
 {orders.some(o=>o.status==='completado'&&!termsMap.get(o.id)?.completed_on)&&<p className="fin-warning">Hay pedidos finalizados sin fecha de finalización. Completa «Estado y fechas» para incluirlos en la utilidad del mes correspondiente.</p>}
 <article className="fin-card"><h3>Utilidad estimada por sección</h3>{filteredProfit.some(r=>r.profit!==null&&(r.revenue||r.fixedCost||r.refunds))?<div className="fin-profit-chart" style={{height:Math.max(240,filteredProfit.filter(r=>r.profit!==null).length*43)}}><ResponsiveContainer width="100%" height="100%"><BarChart layout="vertical" data={filteredProfit.filter(r=>r.profit!==null)} margin={{left:0,right:30,top:15,bottom:0}}><CartesianGrid horizontal={false} stroke="#eadfd8"/><XAxis type="number" tickFormatter={shortMoney}/><YAxis dataKey="name" type="category" width={135} tick={{fontSize:11}}/><Tooltip formatter={chartMoney}/><ReferenceLine x={0} stroke="#796158"/><Bar name="Utilidad estimada" dataKey="profit" fill="#927e68" radius={[0,5,5,0]} isAnimationActive={false}/></BarChart></ResponsiveContainer></div>:<Empty>Finaliza pedidos y completa los costos para ver la comparación.</Empty>}
 {table(['Sección','Ventas netas','Unidades','Costos variables + comisión','Costos fijos','Utilidad estimada','Margen'],filteredProfit.map(r=><tr key={r.id}><td><strong>{r.name}</strong><button className="fin-text-button" onClick={()=>setDialog({type:'cost',section:r.id})}>{r.plan?'Revisar costos':'Completar costos'}</button></td><td>{money(r.netRevenue)}</td><td>{r.units}</td><td>{r.plan?money(r.variableCost+r.fees):'Sin configurar'}</td><td>{r.plan?money(r.fixedCost):'Sin configurar'}</td><td className={(r.profit??0)<0?'fin-negative':'fin-positive'}>{r.profit===null?'—':money(r.profit)}</td><td>{r.margin===null?'—':`${r.margin.toFixed(1)}%`}</td></tr>))}</article>
 <div className="fin-guide"><Info size={20}/><div><strong>Cómo se calcula</strong><p>Ventas finalizadas − devoluciones − (unidades × costo variable promedio) − comisiones estimadas − costos fijos del plan. General reúne los costos compartidos; no se reparten automáticamente entre secciones. El total de todas las secciones sí los incluye.</p><p>Los cobros sin pedido solo aparecen en caja. Las compras de inventario pagadas se muestran en Gastos; aquí se usa el costo estimado de las unidades finalizadas, para no contar ambas cosas dos veces. No es un estado contable ni calcula impuestos.</p></div></div>
 <article className="fin-card"><h3>Comparación de caja por sección</h3>{table(['Sección','Cobros netos','Gastos pagados','Flujo operativo'],monthlyRows.map(r=><tr key={r.id}><td>{r.name}</td><td>{money(r.net)}</td><td>{money(r.expense)}</td><td className={r.operating<0?'fin-negative':'fin-positive'}>{money(r.operating)}</td></tr>))}</article>
 </>}
 {tab==='costs'&&<>
 <SectionHeading title="Ponle números a cada diseño" description="Define promedios por sección para estimar tu utilidad y saber cuántas unidades necesitas vender para cubrir tus costos."/>
 <div className="fin-budget-grid">{sections.filter(s=>matches(s.id)).map(s=>{const plan=plans.find(p=>p.month.startsWith(month)&&p.section_id===s.id),m=plan?costMetrics(plan):null;return <article key={s.id} className="fin-card"><span className="fin-badge">{s.id===GENERAL?'Costos compartidos':'Plan de costos'}</span><h3>{s.name}</h3>{plan&&m?<><dl className="fin-totals"><div><dt>Precio promedio</dt><dd>{money(m.price)}</dd></div><div><dt>Costo variable / unidad</dt><dd>{money(m.cost)}</dd></div><div><dt>Comisión</dt><dd>{plan.fee_percent}%</dd></div><div><dt>Aporte / unidad</dt><dd>{money(m.contribution)}</dd></div><div><dt>Costos fijos / mes</dt><dd>{money(m.fixed)}</dd></div><div><dt>Punto de equilibrio</dt><dd>{s.id===GENERAL?'Costo compartido':m.breakEven===null?'No cubre costo variable':`${m.breakEven} unidades`}</dd></div><div><dt>Utilidad con {plan.expected_units} unidades</dt><dd>{money(m.forecast)}</dd></div></dl>{m.contribution<=0&&s.id!==GENERAL&&<p className="fin-warning">Revisa el precio o el costo: vender más no cubre los costos fijos.</p>}{plan.notes&&<p className="fin-note">{plan.notes}</p>}</>:<p className="fin-note">{s.id===GENERAL?'Registra aquí los costos fijos compartidos. Si no tienes, guarda un plan con cero para confirmarlo.':'Aún no hay costos configurados. Incluye materiales, trabajo, empaque y merma.'}</p>}<Button variant="outline" onClick={()=>setDialog({type:'cost',section:s.id})}>{plan?'Editar costos':'Calcular y guardar'}</Button></article>;})}</div>
 <div className="fin-guide"><BarChart3 size={22}/><p>El margen es la utilidad dividida entre las ventas; no es lo mismo que sumar un porcentaje al costo. El punto de equilibrio redondea hacia arriba las unidades necesarias para cubrir los costos fijos. En secciones con productos distintos, usa un promedio representativo y revísalo cada mes.</p></div>
 </>}
 </div>
 {dialog&&<FinanceDialogs key={JSON.stringify(dialog)} dialog={dialog} data={data} month={month} defaultSection={section} onClose={()=>setDialog(null)} onSaved={async()=>{setNotice('Registro guardado.');await refresh();}}/>}
 </section>;
}
