"use client";

import { useEffect, useMemo, useState } from "react";
import ProductImage from "@/app/product-image";
import "./catalog-cards.css";
import {scrollToSection} from "@/lib/motion";
import { baseProducts, type Product } from "@/lib/catalog";

const sizes=[{label:"40 cm",price:80},{label:"50 cm",price:100,badge:"Más elegida"},{label:"60 cm",price:120},{label:"70 cm",price:150},{label:"80 cm",price:180}];
const themes=[{value:"all",label:"Todos",icon:"✦"},{value:"animalitos",label:"Animalitos",icon:"♧"},{value:"personajes-aventuras",label:"Personajes y aventuras",icon:"★"},{value:"princesas-fantasia",label:"Princesas y fantasía",icon:"♕"},{value:"dinosaurios",label:"Dinosaurios",icon:"◇"},{value:"bebe-delicados",label:"Bebé y delicados",icon:"☁"},{value:"otros",label:"Ocasiones y otros",icon:"♡"}];
const audiences=[{value:"all",label:"Ver todos",icon:"✦",helper:"Todos los diseños"},{value:"niña",label:"Niña",icon:"♡",helper:"Diseños para niña"},{value:"niño",label:"Niño",icon:"☆",helper:"Diseños para niño"},{value:"unisex",label:"Unisex",icon:"☁",helper:"Para cualquier estilo"}];
const deliverySources=[
  ["https://segeda-nubes-tematicas.mad-elynnlevon7.chatgpt.site/entrega-real-01.jpg","Entrega coordinada","Pedido recibido directamente por nuestra clienta.",""],
  ["https://segeda-nubes-tematicas.mad-elynnlevon7.chatgpt.site/entrega-real-02.png","Pedido protegido","La nube viaja envuelta para cuidar cada pieza.",""],
  ["https://segeda-nubes-tematicas.mad-elynnlevon7.chatgpt.site/entrega-real-03.png","Entrega verificada","Pedido personalizado entregado correctamente.","22%"],
  ["https://segeda-nubes-tematicas.mad-elynnlevon7.chatgpt.site/entrega-real-04.png","Clienta satisfecha","Una nube creada especialmente para su familia.","20%"],
  ["https://segeda-nubes-tematicas.mad-elynnlevon7.chatgpt.site/entrega-real-05.png","Producto terminado","Nombre, temática y detalles revisados antes de entregar.","18%"],
  ["https://segeda-nubes-tematicas.mad-elynnlevon7.chatgpt.site/entrega-real-06.png","Entrega segura","Coordinamos cada pedido de manera directa.","18%"],
  ["https://segeda-nubes-tematicas.mad-elynnlevon7.chatgpt.site/entrega-real-07.png","Pedido recibido","Nube personalizada entregada y protegida.","17%"],
  ["https://segeda-nubes-tematicas.mad-elynnlevon7.chatgpt.site/entrega-real-08.png","Entrega real","Clientes reales recibiendo sus pedidos Segeda Home.","17%"],
  ["https://segeda-nubes-tematicas.mad-elynnlevon7.chatgpt.site/entrega-real-09.png","Diseño personalizado","Cada nombre y temática se prepara con cuidado.",""],
  ["https://segeda-nubes-tematicas.mad-elynnlevon7.chatgpt.site/entrega-real-10.png","Entrega confirmada","Pedido terminado y entregado directamente.",""],
];
import {getCatalog} from '@/lib/supabase';

const themeNames:Record<string,string>={animalitos:"Animalitos","personajes-aventuras":"Personajes y aventuras","princesas-fantasia":"Princesas y fantasía",dinosaurios:"Dinosaurios","bebe-delicados":"Bebé y delicados",otros:"Ocasiones y otros"};

export default function NubesClient(){
  const initial=useMemo(()=>baseProducts.filter((product)=>product.category==="nubes").sort((a,b)=>Number(a.id)-Number(b.id)),[]);
  const [products,setProducts]=useState<Product[]>(initial);
  const [selected,setSelected]=useState<Product>(initial[0]);
  const [audience,setAudience]=useState("all");
  const [theme,setTheme]=useState("all");
  const [query,setQuery]=useState("");
  const [visible,setVisible]=useState(12);
  const [size,setSize]=useState(sizes[1]);
  const [name,setName]=useState("");
  const [customTheme,setCustomTheme]=useState(initial[0]?.title||"");
  const [city,setCity]=useState("");
  const [stars,setStars]=useState(false);
  const [notice,setNotice]=useState("");

  useEffect(()=>{getCatalog().then((data)=>{const next=(data.products||[]).filter((product)=>product.category==="nubes").sort((a,b)=>Number(a.id)-Number(b.id));if(next.length){setProducts(next);setSelected((current)=>next.find((product)=>String(product.id)===String(current?.id))||next[0])}}).catch(()=>{})},[]);
  const filtered=useMemo(()=>{const search=query.trim().toLowerCase();return products.filter((product)=>(audience==="all"||product.audience===audience)&&(theme==="all"||product.themeGroup===theme)&&(!search||`${product.title} ${product.tags||""} ${product.themeGroup||""}`.toLowerCase().includes(search)))},[products,audience,theme,query]);
  const previewList=filtered.length?filtered:products;
  const selectedIndex=Math.max(0,previewList.findIndex((product)=>String(product.id)===String(selected?.id)));
  const total=size.price+(stars?25:0);
  const choose=(product:Product)=>{setSelected(product);setCustomTheme(product.title);scrollToSection("personalizar")};
  const custom=()=>{setCustomTheme("");scrollToSection("personalizar");setTimeout(()=>document.getElementById("custom-theme")?.focus(),650)};
  const move=(offset:number)=>{const next=previewList[selectedIndex+offset];if(next){setSelected(next);setCustomTheme(next.title)}};
  const order=()=>{if(!name.trim()||!customTheme.trim()||!city.trim()){setNotice("Completa el nombre, la temática y tu ciudad.");setTimeout(()=>setNotice(""),3200);return}const text=`Hola Segeda Home, quiero pedir una nube temática ☁️✨\n\n*Modelo:* ${selected.title}\n*Código:* NUBES-${String(selected.id).padStart(3,"0")}\n*Medida:* ${size.label}\n*Nombre:* ${name.trim()}\n*Temática:* ${customTheme.trim()}\n*Ciudad:* ${city.trim()}${stars?"\n*Complemento:* 80 stickers de estrellas · S/25":""}\n\n*Total del producto: S/${total}*\n*Confirmación:* 50% de adelanto\n*Elaboración:* 5 a 7 días\n\nQuiero coordinar el diseño y la entrega.`;location.href=`https://wa.me/51978642447?text=${encodeURIComponent(text)}`};

  return <main className="nubes-landing">
    <div className="nubes-promo"><a href="/catalogo">← Tienda completa</a><span>✦ Nubes personalizadas desde <b>S/80</b></span><span>5–7 días de elaboración</span><span>Envíos a todo el Perú</span></div>
    <header className="nubes-header"><a className="nubes-brand" href="#modelos"><ProductImage src="/segeda-logo.jpg" alt="Segeda Home" loading="eager" fit="cover"/><span><strong>Segeda Home</strong><small>Nubes temáticas</small></span></a><nav><a href="#modelos">Nubes temáticas</a><a href="#como-pedir">Cómo funciona</a><a href="#precios">Tamaños</a><a href="#entregas">Inspiración</a><a href="#preguntas">Preguntas frecuentes</a></nav><button onClick={()=>scrollToSection("personalizar")}>♡ Crear mi nube</button></header>
    <nav className="nubes-category-mirror" aria-label="Otras colecciones"><a href="/navidad">❋ Preventa Navideña</a><a href="/catalogo?categoria=placas">○ Placas circulares</a><a href="/catalogo?categoria=cuadros">▣ Cuadros infantiles</a><a href="/catalogo?categoria=combo220">✦ Combo completo</a><a href="/catalogo?categoria=lamparas">☼ Lámparas</a></nav>
    <section className="nubes-models" id="modelos"><SectionHeading kicker="Elige en pocos pasos" title="Encuentra su mundo favorito" text={`${products.length} diseños para iluminar su habitación. Elige una temática y la hacemos suya.`}/><div className="buy-guide" aria-label="Pasos para comprar"><span className="active"><b>1</b><small>Busca la temática</small></span><i>→</i><span><b>2</b><small>Elige el modelo</small></span><i>→</i><span><b>3</b><small>Medida y nombre</small></span></div>
      <div className="audience-selector"><div><small>Primero elige para quién</small><strong>¿Qué modelos quieres ver?</strong></div><div>{audiences.map((option)=>{const count=option.value==="all"?products.length:products.filter((product)=>product.audience===option.value).length;return <button key={option.value} className={audience===option.value?"active":""} aria-pressed={audience===option.value} onClick={()=>{setAudience(option.value);setTheme("all");setVisible(12)}}><i>{option.icon}</i><span><strong>{option.label}</strong><small>{option.helper}</small></span><b>{count}</b></button>})}</div></div>
      <label className="visual-search"><span>⌕</span><div><small>¿Qué temática buscas?</small><input value={query} onChange={(event)=>{setQuery(event.target.value);setVisible(12)}} placeholder="Ejemplo: Goku, safari, sirenita…"/></div>{query&&<button aria-label="Limpiar búsqueda" onClick={()=>setQuery("")}>×</button>}</label>
      <div className="theme-filters">{themes.map((option)=>{const base=audience==="all"?products:products.filter((product)=>product.audience===audience);const count=option.value==="all"?base.length:base.filter((product)=>product.themeGroup===option.value).length;return <button key={option.value} className={theme===option.value?"active":""} aria-pressed={theme===option.value} onClick={()=>{setTheme(option.value);setVisible(12)}}><i>{option.icon}</i><span>{option.label}</span><b>{count}</b></button>})}</div>
      <button className="custom-theme-cta" onClick={custom}><span>✦</span><strong>¿No encuentras tu temática?</strong><b>Personaliza aquí</b><i>→</i></button>
      {!filtered.length?<div className="empty-search"><span>☁</span><h3>No encontramos esa temática</h3><p>Podemos diseñarla especialmente para ti.</p><button onClick={custom}>Personalizar mi idea →</button></div>:<div className="model-grid" key={`${audience}-${theme}`}>{filtered.slice(0,visible).map((product)=><button key={product.id} className={String(selected?.id)===String(product.id)?"model-card selected":"model-card"} onClick={()=>choose(product)}><span className="model-image"><ProductImage src={product.imageUrl} alt={product.title} fit="cover"/><i>{String(selected?.id)===String(product.id)?"✓ Elegido":"Elegir"}</i></span><small>{themeNames[product.themeGroup||""]||"Ocasiones y otros"} · <span className="model-code">NUBES-{String(product.id).padStart(3,"0")}</span></small><strong>{product.title}</strong><span>Personalizable desde <b>S/80</b></span></button>)}</div>}
      {!!filtered.length&&<div className="models-summary"><span>Mostrando <b>{Math.min(visible,filtered.length)}</b> de <b>{filtered.length}</b> diseños</span>{visible<filtered.length&&<button onClick={()=>setVisible((value)=>Math.min(value+12,filtered.length))}>Ver más diseños ↓</button>}</div>}
    </section>
    <section className="nubes-order" id="personalizar"><div className="order-copy" id="precios"><p className="eyebrow">Personaliza y conoce el precio</p><h2>Dale su nombre.<br/>Hazla suya.</h2><p>Elige la medida, dinos su nombre y cuéntanos tu idea. Coordinamos contigo cada detalle antes de crearla.</p><div className="size-grid">{sizes.map((option)=><button key={option.label} className={size.label===option.label?"active":""} onClick={()=>setSize(option)}><span>{option.label}</span><strong>S/{option.price}</strong>{option.badge&&<i>{option.badge}</i>}</button>)}</div><div className="includes"><b>El precio incluye:</b><span>Nombre personalizado</span><span>Personaje o temática</span><span>Luces cálidas a pilas</span><span>Piezas en alto relieve</span></div></div>
      <div className="order-card"><div className="selected-preview"><div className="selected-preview-image"><ProductImage src={selected?.galleryUrls?.[0]||selected?.imageUrl} alt={`Vista completa de ${selected?.title||"nube temática"}`} loading="eager"/></div><div className="preview-controls"><button disabled={selectedIndex===0} onClick={()=>move(-1)}>‹</button><span>Modelo {selectedIndex+1} de {previewList.length}<small>Usa las flechas para cambiar</small></span><button disabled={selectedIndex===previewList.length-1} onClick={()=>move(1)}>›</button></div><div><small>Modelo elegido</small><strong>{selected?.title}</strong><span>NUBES-{String(selected?.id).padStart(3,"0")}</span></div></div>
        <label>Nombre que llevará la nube<input value={name} onChange={(event)=>setName(event.target.value)} placeholder="Ejemplo: Valentina"/></label><label>Personaje o temática<input id="custom-theme" value={customTheme} onChange={(event)=>setCustomTheme(event.target.value)} placeholder="Ejemplo: Sirenita, dinosaurio…"/></label><label>Ciudad de entrega<input value={city} onChange={(event)=>setCity(event.target.value)} placeholder="Ejemplo: Lima, Arequipa…"/></label>
        <button className={stars?"nubes-addon active":"nubes-addon"} onClick={()=>setStars((value)=>!value)}><span>★</span><div><strong>80 stickers de estrellas</strong><small>Complemento opcional</small></div><b>+S/25</b><i>{stars?"✓":"+"}</i></button><div className="advance-notice"><span>50%</span><div><strong>Confirma tu pedido con el 50% de adelanto</strong><small>Iniciamos el diseño y la elaboración después de confirmar el pago.</small></div></div><div className="nubes-total"><span>Total del producto</span><strong>S/{total}</strong></div><button className="nubes-whatsapp" onClick={order}>Pedir por WhatsApp →</button><small className="order-note">Antes de elaborar coordinamos contigo el diseño y la entrega.</small>
      </div>
    </section>
    <section className="deliveries" id="entregas"><SectionHeading kicker="Fotos reales de nuestros pedidos" title="De nuestras manos a su hogar" text="Así llegan nuestras nubes: protegidas, personalizadas y listas para encontrar su lugar."/><div className="delivery-gallery">{deliverySources.map(([image,title,text,mask],index)=><figure key={image}><div className="delivery-photo"><ProductImage src={image} alt={`Entrega real de nube temática personalizada ${index+1}`} fit="cover"/>{mask&&<span className="privacy-mask" style={{height:mask}}>Dirección protegida</span>}</div><figcaption><span>✓ Entrega real</span><b>{title}</b><small>{text}</small></figcaption></figure>)}</div><div className="delivery-trust">{[["♡","Empaque protegido","Cuidamos las piezas durante el traslado."],["✓","Coordinación directa","Confirmamos los detalles contigo por WhatsApp."],["⌂","Envíos a todo el Perú","Por Olva Courier o Shalom."]].map(([icon,title,text])=><article key={title}><span>{icon}</span><div><b>{title}</b><small>{text}</small></div></article>)}</div><p className="delivery-note">Por privacidad, no mostramos direcciones ni datos personales de nuestros clientes.</p></section>
    <section className="nubes-steps" id="como-pedir"><SectionHeading kicker="Fácil, rápido y personalizado" title="De tu idea a su habitación"/>
      <div>{[["01","♡","Elige y personaliza","Selecciona modelo, medida, nombre y temática."],["02","✦","Confirma con el 50%","Coordinamos el diseño y confirmas tu pedido con el adelanto."],["03","⌂","Elaboramos y enviamos","Lo preparamos en 5–7 días y coordinamos el envío."]].map(([number,icon,title,text])=><article key={number}><b>{number}</b><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="nubes-faq" id="preguntas"><SectionHeading kicker="Antes de pedir" title="Te acompañamos en cada detalle"/><div>{[["¿Puedo pedir cualquier personaje?","Sí. Personalizamos el personaje, nombre y colores según tu idea."],["¿Cómo funcionan las luces?","Funcionan a pilas y quedan ocultas detrás del MDF."],["¿Cuánto demora?","La elaboración habitual es de 5 a 7 días, previa confirmación."],["¿Cómo confirmo mi pedido?","Todo pedido se confirma con el 50% de adelanto. El saldo se coordina antes del envío o entrega."],["¿Envían a provincia?","Sí, por Olva Courier o Shalom a todo el Perú."]].map(([question,answer],index)=><details key={question} open={index===0}><summary>{question}<span>+</span></summary><p>{answer}</p></details>)}</div></section>
    <section className="nubes-closing"><div><p>¿Tienes otra temática en mente?</p><h2>La diseñamos especialmente para ti.</h2><span>Cuéntanos tu idea y te orientamos por WhatsApp.</span></div><a href="https://wa.me/51978642447?text=Hola%20Segeda%20Home%2C%20tengo%20una%20idea%20especial%20para%20una%20nube%20personalizada">Cuéntanos tu idea →</a></section>
    <footer className="nubes-footer"><a href="#modelos"><ProductImage src="/segeda-logo.jpg" alt="Segeda Home" fit="cover"/><span><strong>Segeda Home</strong><small>Ilusión hecha decoración</small></span></a><p>Nubes temáticas personalizadas · Envíos a todo el Perú.</p></footer>
    <button className="nubes-floating" onClick={()=>scrollToSection("personalizar")}><ProductImage src={selected?.imageUrl} alt=""/><span><small>Modelo elegido</small><strong>{selected?.title}</strong></span><b>{size.label} · S/{total}</b><i>Continuar →</i></button>
    {notice&&<div className="nubes-notice">{notice}</div>}
  </main>;
}

function SectionHeading({kicker,title,text}:{kicker:string;title:string;text?:string}){return <div className="nubes-section-heading"><p>{kicker}</p><h2>{title}</h2>{text&&<span>{text}</span>}</div>}
